homepage:
  pattern:  /
  defaults: { _controller: SGLiveChatBundle:Default:index }

# -- Live Chat -----------------------------------------------------------------

sglc_chat_homepage:
    pattern:  /sglivechat
    defaults: { _controller: SGLiveChatBundle:Chat:index }

sglc_chat_invite:
  pattern: /sglivechat/{sessId}/invite
  defaults: { _controller: SGLiveChatBundle:Chat:invite }

sglc_chat_invite_accept:
  pattern: /sglivechat/{id}/invite/accept
  defaults: { _controller: SGLiveChatBundle:Chat:acceptInvite }

sglc_chat_invite_reject:
  pattern: /sglivechat/{id}/invite/reject
  defaults: { _controller: SGLiveChatBundle:Chat:rejectInvite }

sglc_chat_load:
  pattern: /sglivechat/{id}/load
  defaults: { _controller: SGLiveChatBundle:Chat:load }

sglc_chat_accept:
  pattern: /sglivechat/{id}/accept
  defaults: { _controller: SGLiveChatBundle:Chat:accept }

sglc_chat_reject:
  pattern: /sglivechat/{id}/reject/
  defaults: { _controller: SGLiveChatBundle:Chat:reject }
  
sglc_chat_user_action:
  pattern: /sglivechat/{id}/user/action/{action}
  defaults: { _controller: SGLiveChatBundle:Chat:userAction }

sglc_chat_done:
  pattern: /sglivechat/{id}/done
  defaults: { _controller: SGLiveChatBundle:Chat:done }

sglc_chat_send:
  pattern: /sglivechat/{id}/send
  defaults: { _controller: SGLiveChatBundle:Chat:send }
  requirements: { _method: post }

sglc_chat_messages:
  pattern: /sglivechat/{id}/messages.{_format}
  defaults: { _controller: SGLiveChatBundle:Chat:messages, _format: html }
  requirements: { _method: get }
  
sglc_chat_status:
  pattern: /sglivechat/status
  defaults: { _controller: SGLiveChatBundle:Chat:status }
  requirements: { _method: get }


# -- Tracker -------------------------------------------------------------------

sglc_track_index:
  pattern: /js/sglivechat-tracker
  defaults: { _controller: SGLiveChatBundle:Track:index }
  requirements: { _method: get }

sglc_track_updater:
  pattern: /js/sglivechat-tracker/update
  defaults: { _controller: SGLiveChatBundle:Track:update }

sglc_track_reset:
  pattern: /js/sglivechat-tracker/reset
  defaults: { _controller: SGLiveChatBundle:Track:reset }
sglc_track_status:
  pattern: /js/sglivechat-tracker/status.{_format}
  defaults: { _controller: SGLiveChatBundle:Track:status, _format: html }

# -- Admin ---------------------------------------------------------------------

sglc_admin_index:
  pattern: /admin/sglivechat
  defaults: { _controller: SGLiveChatBundle:Admin:index }
  requirements: { _method: get }

sglc_admin_logout:
  pattern: /admin/sglivechat/logout
  defaults: { _controller: SGLiveChatBundle:Admin:logout }
  requirements: { _method: get }

#sglc_admin_login:
#  pattern: /admin/sglivechat/login
#  defaults: { _controller: SGLiveChatBundle:Admin:login }


#sglc_admin_check_login:
#  pattern: /admin/sglivechat/login/check
#  defaults: { _controller: SGLiveChatBundle:Admin:checkLogin }
  
_security_login:
  pattern: /admin/sglivechat/login
  defaults: { _controller: SGLiveChatBundle:Admin:login }

_security_check:
  pattern: /admin/sglivechat/login/check
  defaults: { _controller: SGLiveChatBundle:Admin:checkLogin }
  requirements: { _method: post }

sglc_admin_operator:
  pattern: /admin/sglivechat/operator
  defaults: { _controller: SGLiveChatBundle:Admin:operator }

sglc_admin_operator_departments:
  pattern: /admin/sglivechat/operator/departments/{page}
  defaults: { _controller: SGLiveChatBundle:Admin:operatorDepartments, page: 1 }

sglc_admin_operator_department:
  pattern: /admin/sglivechat/operator/department
  defaults: { _controller: SGLiveChatBundle:Admin:operatorDepartment }
  

sglc_admin_operator_department_edit:
  pattern: /admin/sglivechat/operator/department/{id}
  defaults: { _controller: SGLiveChatBundle:Admin:operatorDepartment }

sglc_admin_operator_edit:
  pattern: /admin/sglivechat/operator/{id}
  defaults: { _controller: SGLiveChatBundle:Admin:operator }

sglc_admin_operators:
  pattern: /admin/sglivechat/operators/{page}
  defaults: { _controller: SGLiveChatBundle:Admin:operators, page: 1 }
  requirements: { page: \d+ }

sglc_admin_canned_message:
  pattern: /admin/sglivechat/canned-message
  defaults: { _controller: SGLiveChatBundle:Admin:cannedMessage }

sglc_admin_canned_message_edit:
  pattern: /admin/sglivechat/canned-message/{id}
  defaults: { _controller: SGLiveChatBundle:Admin:cannedMessage }
  
sglc_admin_canned_messages:
  pattern: /admin/sglivechat/canned-messages/{page}
  defaults: { _controller: SGLiveChatBundle:Admin:cannedMessages, page: 1}
  requirements: { page: \d+ }

sglc_admin_console_sessions:
  pattern: /admin/sglivechat/console/sessions
  defaults: { _controller: SGLiveChatBundle:Admin:sessions }

sglc_admin_console_requested_chats:
  pattern: /admin/sglivechat/console/requested-chats.{_format}
  defaults: { _controller: SGLiveChatBundle:Admin:requestedChats, _format: html }

sglc_admin_console_current_visits:
  pattern: /admin/sglivechat/console/current-visits.{_format}
  defaults: { _controller: SGLiveChatBundle:Admin:currentVisits, _format: html }

sglc_admin_console_sessions_service:
  pattern: /admin/sglivechat/console/sessions-service.json
  defaults: { _controller: SGLiveChatBundle:Admin:sessionsService }

sglc_admin_console_close:
  pattern: /admin/sglivechat/console/close/{id}
  defaults: { _controller: SGLiveChatBundle:Admin:closeChat }